edit: Connexion_BD.class ChambreBD.class View.class Projet.class Controleur.class


ChambreBD.class: ChambreBD.java
	javac ChambreBD.java
Connexion_BD.class: Connexion_BD.java
	javac Connexion_BD.java
Projet.class: Projet.java
	javac Projet.java
Controleur.class: Controleur.java 
	javac Controleur.java
View.class: View.java
	javac View.java


run:
	java -cp "../mariadb-client.jar:." Projet

clean:
	rm *.class
