edit: View.class ActionBoutton.class ActionBouttonNonPres.class BaseDonnee.class BaseDonneeNonPres.class MainOccupation.class MainNonPres.class ActionValide.class RecupererPeriode.class Courbe.class MainPeriode.class FrameMenu.class Menu.class


Menu.class: Menu.java
	javac Menu.java
FrameMenu.class: FrameMenu.java
	javac FrameMenu.java
View.class: View.java
	javac View.java
MainOccupation.class: MainOccupation.java
	javac MainOccupation.java
BaseDonnee.class: BaseDonnee.java
	javac BaseDonnee.java
ActionBoutton.class: ActionBoutton.java
	javac ActionBoutton.java
MainNonPres.class: MainNonPres.java
	javac MainNonPres.java
ActionBouttonNonPres.class: ActionBouttonNonPres.java
	javac ActionBouttonNonPres.java
BaseDonneeNonPres.class: BaseDonneeNonPres.java
	javac BaseDonneeNonPres.java
RecupererPeriode.class: RecupererPeriode.java
	javac RecupererPeriode.java
Courbe.class: Courbe.java
	javac Courbe.java
MainPeriode.class: MainPeriode.java
	javac MainPeriode.java
ActionValide.class: ActionValide.java
	javac ActionValide.java

run:
	java -cp "../mariadb-client.jar:." Menu

clean:
	rm *.class
